In [1]:
import numpy as np
import pandas as pd

In [2]:
rainfall_df = pd.read_csv(r"D:\CS 6th sem books\Summer2026\Weather_Analysis\data\raw\ABD_Rainfall_1981_2025_PAK.csv")
weather_df = pd.read_csv(r"D:\CS 6th sem books\Summer2026\Weather_Analysis\data\raw\weather.csv")

In [3]:
rainfall_df["Date"] = pd.to_datetime(rainfall_df["Date"],errors="coerce")
rainfall_df["Date"] = rainfall_df["Date"].dt.date

C:\Users\New Ameen Computer\AppData\Local\Temp\ipykernel_22264\1081656417.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  rainfall_df["Date"] = pd.to_datetime(rainfall_df["Date"],errors="coerce")

In [4]:
rainfall_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56176 entries, 0 to 56175
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             56175 non-null  object
 1   PCODE            56175 non-null  object
 2   Country          56176 non-null  object
 3   Rainfall - (MM)  56175 non-null  float64
 4   Province         56175 non-null  object
 5   City             56175 non-null  object
 6   Year             56175 non-null  float64
 7   Month            56175 non-null  object
 8   Quarter          56175 non-null  object
dtypes: float64(2), object(7)
memory usage: 3.9+ MB

In [5]:
rainfall_df.dropna(inplace=True)

In [6]:
rainfall_df.isnull().sum()

Date               0
PCODE              0
Country            0
Rainfall - (MM)    0
Province           0
City               0
Year               0
Month              0
Quarter            0
dtype: int64

In [7]:
rainfall_df.duplicated().sum()

np.int64(145)

In [8]:
rainfall_df.drop_duplicates(inplace=True)

In [9]:
rainfall_df.duplicated().sum()

np.int64(0)

In [10]:
# Drop provincial aggregates (Province = City)
provincial_cities_to_drop = ['Balochistan', 'Sindh', 'Punjab', 'Khyber Pakhtunkhwa']
rainfall_df = rainfall_df[~rainfall_df['City'].isin(provincial_cities_to_drop)]

print(f"After removing provincial aggregates: {len(rainfall_df)} rows")

After removing provincial aggregates: 48150 rows

In [11]:
rainfall_df.reset_index(drop=True,inplace=True)

In [12]:
rainfall_df["Year"] = rainfall_df["Year"].astype(int)

In [13]:
rainfall_df.loc[rainfall_df["Rainfall - (MM)"]<0]

Empty DataFrame
Columns: [Date, PCODE, Country, Rainfall - (MM), Province, City, Year, Month, Quarter]
Index: []

In [14]:
(rainfall_df["Rainfall - (MM)"]<0).sum()

np.int64(0)

In [15]:
rainfall_df.loc[(rainfall_df["Year"]<1981) | (rainfall_df["Year"]>2025)]

Empty DataFrame
Columns: [Date, PCODE, Country, Rainfall - (MM), Province, City, Year, Month, Quarter]
Index: []

In [16]:
balochistan_rows = rainfall_df[(rainfall_df['Province'] == 'Balochistan') & 
                               (rainfall_df['City'] == 'Balochistan')]
print(f"Rows where Province = City = 'Balochistan': {len(balochistan_rows)}")

Rows where Province = City = 'Balochistan': 0

In [17]:
print(balochistan_rows.head(10))

Empty DataFrame
Columns: [Date, PCODE, Country, Rainfall - (MM), Province, City, Year, Month, Quarter]
Index: []

In [18]:
print("\nChecking all Province-City combinations:")
print(rainfall_df[rainfall_df['Province'] == rainfall_df['City']])

Checking all Province-City combinations:
             Date  PCODE   Country  Rainfall - (MM)   Province       City  \
46545  1981-01-01  PK401  Pakistan             33.0  Islamabad  Islamabad
46546  1981-11-01  PK401  Pakistan              7.0  Islamabad  Islamabad
46547  1981-01-21  PK401  Pakistan             95.0  Islamabad  Islamabad
46548  1981-01-02  PK401  Pakistan             52.0  Islamabad  Islamabad
46549  1981-11-02  PK401  Pakistan             17.0  Islamabad  Islamabad
...           ...    ...       ...              ...        ...        ...
48145  2025-11-06  PK401  Pakistan              6.0  Islamabad  Islamabad
48146  2025-06-21  PK401  Pakistan            110.0  Islamabad  Islamabad
48147  2025-01-07  PK401  Pakistan            196.0  Islamabad  Islamabad
48148  2025-11-07  PK401  Pakistan            154.0  Islamabad  Islamabad
48149  2025-07-21  PK401  Pakistan            141.0  Islamabad  Islamabad

       Year     Month Quarter
46545  1981   January      Q3
46546  1981   January      Q3
46547  1981   January      Q3
46548  1981  February      Q3
46549  1981  February      Q3
...     ...       ...     ...
48145  2025      June      Q4
48146  2025      June      Q4
48147  2025      July      Q1
48148  2025      July      Q1
48149  2025      July      Q1

[1605 rows x 9 columns]

In [19]:
provincial_cities_to_drop = ['Balochistan', 'Sindh', 'Punjab', 'Khyber Pakhtunkhwa']

In [20]:
print(f"Original rows: {len(rainfall_df)}")

Original rows: 48150

In [21]:
rainfall_df = rainfall_df[~rainfall_df['City'].isin(provincial_cities_to_drop)]

In [22]:
print(f"Rows after dropping provincial aggregates: {len(rainfall_df)}")

Rows after dropping provincial aggregates: 48150

In [23]:
print(f"\nIslamabad rows remaining: {len(rainfall_df[rainfall_df['City'] == 'Islamabad'])}")

Islamabad rows remaining: 1605

In [24]:
print("Provinces:", rainfall_df['Province'].unique())

Provinces: ['Punjab' 'Khyber Pakhtunkhwa' 'Sindh' 'Balochistan' 'Islamabad']

In [25]:
rainfall_df.to_csv("D:\CS 6th sem books\Summer2026\Weather_Analysis\data\proccessed/cleaned_rainfall.csv")

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\New Ameen Computer\AppData\Local\Temp\ipykernel_22264\1928758247.py:1: SyntaxWarning: invalid escape sequence '\C'
  rainfall_df.to_csv("D:\CS 6th sem books\Summer2026\Weather_Analysis\data\proccessed/cleaned_rainfall.csv")

In [26]:
weather_df.head(500)

,date,temp_max,temp_min,rain,solar_radiation,city
0,2013-12-31 19:00:00+00:00,13.877000,1.127000,0.0,12.69,Rawalpindi
1,2014-01-01 19:00:00+00:00,16.677000,1.677000,0.0,12.88,Rawalpindi
2,2014-01-02 19:00:00+00:00,16.876999,0.227000,0.0,13.09,Rawalpindi
3,2014-01-03 19:00:00+00:00,16.026999,3.077000,0.0,11.17,Rawalpindi
4,2014-01-04 19:00:00+00:00,16.927000,1.427000,0.0,12.61,Rawalpindi
...,...,...,...,...,...,...
495,2015-05-10 19:00:00+00:00,32.977000,19.577000,2.1,14.53,Rawalpindi
496,2015-05-11 19:00:00+00:00,25.276999,19.177000,13.2,15.71,Rawalpindi
497,2015-05-12 19:00:00+00:00,26.776999,17.626999,6.5,22.86,Rawalpindi
498,2015-05-13 19:00:00+00:00,28.677000,18.427000,2.1,25.55,Rawalpindi
499,2015-05-14 19:00:00+00:00,30.827000,17.427000,0.0,27.76,Rawalpindi

In [27]:
weather_df.tail(500)

,date,temp_max,temp_min,rain,solar_radiation,city
54295,2022-08-19 19:00:00+00:00,29.919500,27.369501,0.0,19.44,Gwadar
54296,2022-08-20 19:00:00+00:00,30.019500,27.019500,0.0,21.06,Gwadar
54297,2022-08-21 19:00:00+00:00,30.369501,26.969501,0.0,22.98,Gwadar
54298,2022-08-22 19:00:00+00:00,30.219501,26.519500,0.0,23.90,Gwadar
54299,2022-08-23 19:00:00+00:00,30.119501,26.569500,0.0,23.46,Gwadar
...,...,...,...,...,...,...
54790,2023-12-27 19:00:00+00:00,24.919500,19.119501,0.0,13.86,Gwadar
54791,2023-12-28 19:00:00+00:00,25.669500,16.619501,0.0,15.18,Gwadar
54792,2023-12-29 19:00:00+00:00,26.019500,16.219501,0.0,15.01,Gwadar
54793,2023-12-30 19:00:00+00:00,27.819500,16.719501,0.0,15.34,Gwadar
54794,2023-12-31 19:00:00+00:00,24.869501,16.069500,0.0,14.99,Gwadar

In [28]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54795 entries, 0 to 54794
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             54795 non-null  object
 1   temp_max         54795 non-null  float64
 2   temp_min         54795 non-null  float64
 3   rain             54795 non-null  float64
 4   solar_radiation  54795 non-null  float64
 5   city             54795 non-null  object
dtypes: float64(4), object(2)
memory usage: 2.5+ MB

In [29]:
weather_df["date"] = pd.to_datetime(weather_df["date"],errors="coerce")

In [30]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54795 entries, 0 to 54794
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             54795 non-null  datetime64[ns, UTC]
 1   temp_max         54795 non-null  float64
 2   temp_min         54795 non-null  float64
 3   rain             54795 non-null  float64
 4   solar_radiation  54795 non-null  float64
 5   city             54795 non-null  object
dtypes: datetime64[ns, UTC](1), float64(4), object(1)
memory usage: 2.5+ MB

In [31]:
weather_df.head()

,date,temp_max,temp_min,rain,solar_radiation,city
0,2013-12-31 19:00:00+00:00,13.877000,1.127,0.0,12.69,Rawalpindi
1,2014-01-01 19:00:00+00:00,16.677000,1.677,0.0,12.88,Rawalpindi
2,2014-01-02 19:00:00+00:00,16.876999,0.227,0.0,13.09,Rawalpindi
3,2014-01-03 19:00:00+00:00,16.026999,3.077,0.0,11.17,Rawalpindi
4,2014-01-04 19:00:00+00:00,16.927000,1.427,0.0,12.61,Rawalpindi

In [32]:
weather_df["month"] = weather_df["date"].dt.month_name()
weather_df["date"] = weather_df["date"].dt.date

In [33]:
weather_df.head()

,date,temp_max,temp_min,rain,solar_radiation,city,month
0,2013-12-31,13.877000,1.127,0.0,12.69,Rawalpindi,December
1,2014-01-01,16.677000,1.677,0.0,12.88,Rawalpindi,January
2,2014-01-02,16.876999,0.227,0.0,13.09,Rawalpindi,January
3,2014-01-03,16.026999,3.077,0.0,11.17,Rawalpindi,January
4,2014-01-04,16.927000,1.427,0.0,12.61,Rawalpindi,January

In [34]:
weather_df.isnull().sum()

date               0
temp_max           0
temp_min           0
rain               0
solar_radiation    0
city               0
month              0
dtype: int64

In [35]:
weather_df.duplicated().sum()

np.int64(0)

In [36]:
weather_df.loc[weather_df["temp_max"]<weather_df["temp_min"]]

Empty DataFrame
Columns: [date, temp_max, temp_min, rain, solar_radiation, city, month]
Index: []

In [37]:
weather_df.loc[weather_df["rain"]<0]

Empty DataFrame
Columns: [date, temp_max, temp_min, rain, solar_radiation, city, month]
Index: []

In [38]:
weather_df.loc[weather_df["solar_radiation"]<0]

Empty DataFrame
Columns: [date, temp_max, temp_min, rain, solar_radiation, city, month]
Index: []

In [39]:
weather_df["city"].unique()

array(['Rawalpindi', 'Islamabad', 'Abbottabad', 'Gilgit', 'Skardu',
       'Lahore', 'Faisalabad', 'Sialkot', 'Multan', 'Bahawalpur',
       'Karachi', 'Hyderabad', 'Sukkur', 'Quetta', 'Gwadar'], dtype=object)

In [40]:
weather_df.to_csv("D:\CS 6th sem books\Summer2026\Weather_Analysis\data\proccessed\cleaned_weather.csv")

<>:1: SyntaxWarning: invalid escape sequence '\C'
<>:1: SyntaxWarning: invalid escape sequence '\C'
C:\Users\New Ameen Computer\AppData\Local\Temp\ipykernel_22264\2715368474.py:1: SyntaxWarning: invalid escape sequence '\C'
  weather_df.to_csv("D:\CS 6th sem books\Summer2026\Weather_Analysis\data\proccessed\cleaned_weather.csv")

In [41]:
rainfall_df["City"].unique()

array(['Bahawalpur', 'Lakki Marwat', 'D. I. Khan', 'Rajanpur',
       'Malir Karachi', 'Kech', 'South Waziristan', 'Jhang', 'Gujranwala',
       'Kohistan Upper', 'Washuk', 'Kohat', 'Kasur', 'Kambar Shahdad Kot',
       'Chitral Upper', 'Mardan', 'Tharparkar', 'Vehari', 'Kachhi',
       'Nowshera', 'Chagai', 'Attock', 'Okara', 'Bhakkar', 'Dera Bugti',
       'Khairpur', 'Killa Saifullah', 'Jamshoro', 'Sanghar', 'Islamabad'],
      dtype=object)

In [42]:
rainfall_df["City"].nunique()

30

In [43]:
weather_df["city"].unique()

array(['Rawalpindi', 'Islamabad', 'Abbottabad', 'Gilgit', 'Skardu',
       'Lahore', 'Faisalabad', 'Sialkot', 'Multan', 'Bahawalpur',
       'Karachi', 'Hyderabad', 'Sukkur', 'Quetta', 'Gwadar'], dtype=object)

In [44]:
weather_df["city"].nunique()

15

In [45]:
rainfall_cities = set(rainfall_df["City"].str.title().str.strip())
weather_cities = set(weather_df["city"].str.title().str.strip())

common_cities = sorted(rainfall_cities.intersection(weather_cities))

print(common_cities)

['Bahawalpur', 'Islamabad']

In [46]:
weather_df.loc[weather_df["city"]=="Sukkur"]

             date  temp_max  temp_min  rain  solar_radiation    city     month
43836  2013-12-31    17.526     3.976   0.0            15.32  Sukkur  December
43837  2014-01-01    18.776     4.026   0.0            15.41  Sukkur   January
43838  2014-01-02    19.726     4.376   0.0            15.66  Sukkur   January
43839  2014-01-03    22.126     5.826   0.0            15.30  Sukkur   January
43840  2014-01-04    22.026     5.176   0.0            15.49  Sukkur   January
...           ...       ...       ...   ...              ...     ...       ...
47484  2023-12-27    24.850    10.750   0.0            12.77  Sukkur  December
47485  2023-12-28    24.800    11.150   0.0            12.59  Sukkur  December
47486  2023-12-29    22.750    11.600   0.0            12.53  Sukkur  December
47487  2023-12-30    22.150     9.750   0.0            12.67  Sukkur  December
47488  2023-12-31    21.850     9.800   0.0            12.76  Sukkur  December

[3653 rows x 7 columns]

In [47]:
rainfall_df.loc[rainfall_df["City"]=="Sukkur"]

Empty DataFrame
Columns: [Date, PCODE, Country, Rainfall - (MM), Province, City, Year, Month, Quarter]
Index: []

In [48]:
rainfall_df["Date"] = pd.to_datetime(rainfall_df["Date"])
weather_df["date"] = pd.to_datetime(weather_df["date"])

rainfall_start = rainfall_df["Date"].min()
rainfall_end = rainfall_df["Date"].max()

weather_start = weather_df["date"].min()
weather_end = weather_df["date"].max()

In [49]:
rainfall_start = rainfall_df["Date"].min()
rainfall_end = rainfall_df["Date"].max()

weather_start = weather_df["date"].min()
weather_end = weather_df["date"].max()

print("Rainfall dataset:")
print("Earliest:", rainfall_start)
print("Latest:", rainfall_end)

print("\nWeather dataset:")
print("Earliest:", weather_start)
print("Latest:", weather_end)

Rainfall dataset:
Earliest: 1981-01-01 00:00:00
Latest: 2025-11-07 00:00:00

Weather dataset:
Earliest: 2013-12-31 00:00:00
Latest: 2023-12-31 00:00:00

In [50]:
overlap_start = max(rainfall_start, weather_start)
overlap_end = min(rainfall_end, weather_end)

print("\nOverlap period:")
print(overlap_start, "to", overlap_end)

Overlap period:
2013-12-31 00:00:00 to 2023-12-31 00:00:00

rainfall dataset stats

In [51]:
# By city

In [52]:
rainfall_stats_cities = rainfall_df.groupby("City").agg(
    Average_Rainfall=("Rainfall - (MM)", "mean"),
    Maximum_Rainfall=("Rainfall - (MM)", "max"),
    Minimum_Rainfall=("Rainfall - (MM)", "min"),
)

print(rainfall_stats_cities)

                    Average_Rainfall  Maximum_Rainfall  Minimum_Rainfall
City
Attock                     21.892212             179.0               1.0
Bahawalpur                  4.502181              93.0               0.0
Bhakkar                    11.687850             123.0               0.0
Chagai                      2.889097              51.0               0.0
Chitral Upper              16.378193             123.0               1.0
D. I. Khan                  8.244860             139.0               0.0
Dera Bugti                  5.598131             104.0               0.0
Gujranwala                 19.669782             185.0               1.0
Islamabad                  32.504673             272.0               1.0
Jamshoro                    4.292212             172.0               0.0
Jhang                       7.657944              99.0               0.0
Kachhi                      3.138318              76.0               0.0
Kambar Shahdad Kot          2.494081              66.0               0.0
Kasur                      13.260436             171.0               0.0
Kech                        2.598131              42.0               0.0
Khairpur                    3.466044              99.0               0.0
Killa Saifullah             6.633645              80.0               0.0
Kohat                      16.023053             168.0               1.0
Kohistan Upper             25.454206             154.0               1.0
Lakki Marwat               11.276636             141.0               0.0
Malir Karachi               5.213084             194.0               0.0
Mardan                     22.565109             199.0               0.0
Nowshera                   15.444860             129.0               1.0
Okara                       6.629907             100.0               0.0
Rajanpur                    5.858567              99.0               0.0
Sanghar                     4.013707             128.0               0.0
South Waziristan           13.314642             101.0               1.0
Tharparkar                  6.466044             224.0               0.0
Vehari                      4.145171              73.0               0.0
Washuk                      3.371963              57.0               0.0

In [53]:
rainfall_stats_provinces = rainfall_df.groupby("Province").agg(
    Average_Rainfall=("Rainfall - (MM)", "mean"))

print(rainfall_stats_provinces)

                    Average_Rainfall
Province
Balochistan                 4.038214
Islamabad                  32.504673
Khyber Pakhtunkhwa         16.087695
Punjab                     10.589339
Sindh                       4.324195

In [54]:
rainfall_stats_months = rainfall_df.groupby("Month").agg(
    Average_Rainfall=("Rainfall - (MM)", "mean"))

print(rainfall_stats_months)

           Average_Rainfall
Month
April              8.568148
August            25.549495
December           3.550758
February           9.540988
January            7.436049
July              27.446173
June               8.040741
March             11.742963
May                5.046914
November           1.883838
October            2.336869
September         11.388636

In [55]:
rainfall_stats_seasons = rainfall_df.groupby("Quarter").agg(
    Average_Rainfall=("Rainfall - (MM)", "mean"))

print(rainfall_stats_seasons)

         Average_Rainfall
Quarter
Q1              21.506433
Q2               2.590488
Q3               9.573333
Q4               7.218601

In [56]:
#Overall Rainfall dataset stats

In [57]:
print(f"Total records after cleaning : {len(rainfall_df)}")
print(f"Date range from : {rainfall_df["Date"].min()} to : {rainfall_df["Date"].max()}")
print(f"Unique cities : {rainfall_df["City"].nunique()}")
print(f"Average rainfall : {rainfall_df["Rainfall - (MM)"].mean()} MM")
print(f"Maximum rainfall : {rainfall_df["Rainfall - (MM)"].max()} MM")
print(f"Minimum rainfall : {rainfall_df["Rainfall - (MM)"].min()} MM")

Total records after cleaning : 48150
Date range from : 1981-01-01 00:00:00 to : 2025-11-07 00:00:00
Unique cities : 30
Average rainfall : 10.22282450674974 MM
Maximum rainfall : 272.0 MM
Minimum rainfall : 0.0 MM

Weather dataset stats

In [58]:
weather_stats_cities = weather_df.groupby("city").agg(
    Average_Max_Temp=("temp_max", "mean"),
    Average_Min_Temp=("temp_min", "mean"),
    Hottest_Day=("temp_max", "max"),
    Coldest_Day=("temp_min", "min")
)

print(weather_stats_cities)

            Average_Max_Temp  Average_Min_Temp  Hottest_Day  Coldest_Day
city
Abbottabad         21.791687         12.298444    37.257000    -6.158500
Bahawalpur         32.253715         20.417813    46.300000     2.150000
Faisalabad         30.719936         18.917664    46.800000     1.493500
Gilgit             17.247188         10.436072    39.409500   -16.746500
Gwadar             28.830053         22.794781    45.619500     6.369500
Hyderabad          34.089121         21.648620    47.950000     5.900000
Islamabad          26.765923         16.279151    43.967000     1.288000
Karachi            30.085536         22.741517    42.900000     8.900000
Lahore             29.740054         18.189383    46.300000     1.100000
Multan             31.624192         19.907124    47.550000     1.700000
Quetta             23.410528         12.747183    39.514503    -9.035500
Rawalpindi         27.197342         15.758697    44.700000     0.227000
Sialkot            28.428930         17.128902    44.450000     1.067500
Skardu             10.737797          3.601667    34.805500   -23.827501
Sukkur             33.870160         21.240883    48.400000     3.976000

In [59]:
weather_stats_month = weather_df.groupby("month").agg(
    Average_Max_Temp=("temp_max", "mean"),
    Average_Min_Temp=("temp_min", "mean"),
    Hottest_Day=("temp_max", "max"),
    Coldest_Day=("temp_min", "min")
)

print(weather_stats_month)

           Average_Max_Temp  Average_Min_Temp  Hottest_Day  Coldest_Day
month
April             29.467032         17.714810    47.200000   -14.327501
August            32.721995         24.891124    44.100000     4.972500
December          18.282615          7.475562    31.634499   -22.727500
February          19.597052          8.887714    38.000000   -22.977500
January           16.076038          6.177672    30.100000   -23.827501
July              33.610737         25.707092    46.250000     6.872500
June              35.179399         24.870388    48.400000    -3.877500
March             23.756715         13.170006    42.300000   -17.677500
May               33.322694         21.669081    48.300000   -13.077499
November          22.751955         11.965510    38.050000   -21.227500
October           28.561296         17.529436    41.700000   -20.627500
September         31.801121         22.841766    42.800000    -9.777500

In [60]:
avg_solar = weather_df["solar_radiation"].mean()

print("Average Solar Radiation:", round(avg_solar, 2))

Average Solar Radiation: 18.84

In [61]:
monthly_solar = weather_df.groupby("month")["solar_radiation"].mean().round(2)

print(monthly_solar)

month
April        23.67
August       20.57
December     12.18
February     16.20
January      12.65
July         20.90
June         24.42
March        19.64
May          24.98
November     13.61
October      17.36
September    19.89
Name: solar_radiation, dtype: float64

In [62]:
highest_month = monthly_solar.idxmax()
lowest_month = monthly_solar.idxmin()

print("Highest:", highest_month, "-", monthly_solar.max())
print("Lowest:", lowest_month, "-", monthly_solar.min())

Highest: May - 24.98
Lowest: December - 12.18

In [63]:
print(f"Total records after cleaning : {len(weather_df)}")
print(f"Date range from : {weather_df["date"].min()} to : {weather_df["date"].max()}")
print(f"Unique cities : {weather_df["city"].nunique()}")
print(f"Highest Temperature : {weather_df["temp_max"].max()}")
print(f"Lowest Temperature : {weather_df["temp_min"].min()}")

Total records after cleaning : 54795
Date range from : 2013-12-31 00:00:00 to : 2023-12-31 00:00:00
Unique cities : 15
Highest Temperature : 48.4
Lowest Temperature : -23.827501

In [64]:
# Save cleaned datasets
rainfall_df.to_csv("D:\CS 6th sem books\Summer2026\Weather_Analysis\data\proccessed\cleaned_rainfall.csv", index=False)
weather_df.to_csv("D:\CS 6th sem books\Summer2026\Weather_Analysis\data\proccessed\cleaned_weather.csv", index=False)

print("✅ Cleaned datasets saved!")

<>:2: SyntaxWarning: invalid escape sequence '\C'
<>:3: SyntaxWarning: invalid escape sequence '\C'
<>:2: SyntaxWarning: invalid escape sequence '\C'
<>:3: SyntaxWarning: invalid escape sequence '\C'
C:\Users\New Ameen Computer\AppData\Local\Temp\ipykernel_22264\2171278975.py:2: SyntaxWarning: invalid escape sequence '\C'
  rainfall_df.to_csv("D:\CS 6th sem books\Summer2026\Weather_Analysis\data\proccessed\cleaned_rainfall.csv", index=False)
C:\Users\New Ameen Computer\AppData\Local\Temp\ipykernel_22264\2171278975.py:3: SyntaxWarning: invalid escape sequence '\C'
  weather_df.to_csv("D:\CS 6th sem books\Summer2026\Weather_Analysis\data\proccessed\cleaned_weather.csv", index=False)

✅ Cleaned datasets saved!