In [1]:
import numpy as np
import pandas as pd

In [2]:
rainfall_df = pd.read_csv(r"D:\CS 6th sem books\Summer2026\Weather_Analysis\data\raw\ABD_Rainfall_1981_2025_PAK.csv")
weather_df = pd.read_csv(r"D:\CS 6th sem books\Summer2026\Weather_Analysis\data\raw\weather.csv")

In [3]:
rainfall_df.head()

,Date,PCODE,Country,Rainfall - (MM),Province,City,Year,Month,Quarter
0,01-01-81,PK2,Pakistan,6.0,Balochistan,Balochistan,1981.0,January,Q3
1,11-01-81,PK2,Pakistan,6.0,Balochistan,Balochistan,1981.0,January,Q3
2,21-01-81,PK2,Pakistan,9.0,Balochistan,Balochistan,1981.0,January,Q3
3,01-02-81,PK2,Pakistan,15.0,Balochistan,Balochistan,1981.0,February,Q3
4,11-02-81,PK2,Pakistan,5.0,Balochistan,Balochistan,1981.0,February,Q3

In [4]:
rainfall_df.columns

Index(['Date', 'PCODE', 'Country', 'Rainfall - (MM)', 'Province', 'City',
       'Year', 'Month', 'Quarter'],
      dtype='object')

In [5]:
rainfall_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56176 entries, 0 to 56175
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Date             56175 non-null  object
 1   PCODE            56175 non-null  object
 2   Country          56176 non-null  object
 3   Rainfall - (MM)  56175 non-null  float64
 4   Province         56175 non-null  object
 5   City             56175 non-null  object
 6   Year             56175 non-null  float64
 7   Month            56175 non-null  object
 8   Quarter          56175 non-null  object
dtypes: float64(2), object(7)
memory usage: 3.9+ MB

In [6]:
rainfall_df.describe()

       Rainfall - (MM)          Year
count     56175.000000  56175.000000
mean         10.149889   2002.794393
std          17.233654     12.871686
min           0.000000   1981.000000
25%           1.000000   1992.000000
50%           4.000000   2003.000000
75%          12.000000   2014.000000
max         272.000000   2025.000000

In [7]:
rainfall_df.isnull()

,Date,PCODE,Country,Rainfall - (MM),Province,City,Year,Month,Quarter
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
56171,False,False,False,False,False,False,False,False,False
56172,False,False,False,False,False,False,False,False,False
56173,False,False,False,False,False,False,False,False,False
56174,False,False,False,False,False,False,False,False,False
56175,True,True,False,True,True,True,True,True,True

In [8]:
rainfall_df.duplicated().sum()

np.int64(145)

In [9]:
rainfall_df.isnull().sum()

Date               1
PCODE              1
Country            0
Rainfall - (MM)    1
Province           1
City               1
Year               1
Month              1
Quarter            1
dtype: int64

In [10]:
rainfall_df["City"].value_counts()

City
Khyber Pakhtunkhwa    3210
Balochistan           1605
Punjab                1605
Bahawalpur            1605
Lakki Marwat          1605
Sindh                 1605
D. I. Khan            1605
Rajanpur              1605
Malir Karachi         1605
Kech                  1605
South Waziristan      1605
Jhang                 1605
Gujranwala            1605
Kohistan Upper        1605
Washuk                1605
Kohat                 1605
Kasur                 1605
Kambar Shahdad Kot    1605
Chitral Upper         1605
Mardan                1605
Tharparkar            1605
Vehari                1605
Kachhi                1605
Nowshera              1605
Chagai                1605
Attock                1605
Okara                 1605
Bhakkar               1605
Dera Bugti            1605
Khairpur              1605
Killa Saifullah       1605
Jamshoro              1605
Sanghar               1605
Islamabad             1605
Name: count, dtype: int64

In [11]:
rainfall_df["City"].value_counts().count()

np.int64(34)

In [12]:
rainfall_df["Date"] = pd.to_datetime(rainfall_df["Date"] , errors="coerce")

C:\Users\New Ameen Computer\AppData\Local\Temp\ipykernel_11292\2504569908.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  rainfall_df["Date"] = pd.to_datetime(rainfall_df["Date"] , errors="coerce")

In [13]:
print("Earliest date:", rainfall_df['Date'].min())
print("Latest date:", rainfall_df['Date'].max())
print("Number of unique cities:", rainfall_df['City'].nunique())
print("Provinces:", rainfall_df['Province'].unique())

Earliest date: 1981-01-01 00:00:00
Latest date: 2025-11-07 00:00:00
Number of unique cities: 34
Provinces: ['Balochistan' 'Khyber Pakhtunkhwa' 'Punjab' 'Sindh' 'Islamabad' nan]

In [14]:
weather_df.head()

,date,temp_max,temp_min,rain,solar_radiation,city
0,2013-12-31 19:00:00+00:00,13.877000,1.127,0.0,12.69,Rawalpindi
1,2014-01-01 19:00:00+00:00,16.677000,1.677,0.0,12.88,Rawalpindi
2,2014-01-02 19:00:00+00:00,16.876999,0.227,0.0,13.09,Rawalpindi
3,2014-01-03 19:00:00+00:00,16.026999,3.077,0.0,11.17,Rawalpindi
4,2014-01-04 19:00:00+00:00,16.927000,1.427,0.0,12.61,Rawalpindi

In [15]:
weather_df.columns

Index(['date', 'temp_max', 'temp_min', 'rain', 'solar_radiation', 'city'], dtype='object')

In [16]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54795 entries, 0 to 54794
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             54795 non-null  object
 1   temp_max         54795 non-null  float64
 2   temp_min         54795 non-null  float64
 3   rain             54795 non-null  float64
 4   solar_radiation  54795 non-null  float64
 5   city             54795 non-null  object
dtypes: float64(4), object(2)
memory usage: 2.5+ MB

In [17]:
weather_df.describe()

           temp_max      temp_min          rain  solar_radiation
count  54795.000000  54795.000000  54795.000000     54795.000000
mean      27.119478     16.940527      1.470466        18.841218
std        9.789899      9.208379      5.778252         5.570569
min      -16.977500    -23.827501      0.000000         1.090000
25%       21.376500     10.148000      0.000000        14.740000
50%       28.798000     18.150000      0.000000        19.120000
75%       34.100000     24.850000      0.200000        23.060000
max       48.400000     35.050000    304.900020        33.740000

In [18]:
weather_df.isnull()

        date  temp_max  temp_min   rain  solar_radiation   city
0      False     False     False  False            False  False
1      False     False     False  False            False  False
2      False     False     False  False            False  False
3      False     False     False  False            False  False
4      False     False     False  False            False  False
...      ...       ...       ...    ...              ...    ...
54790  False     False     False  False            False  False
54791  False     False     False  False            False  False
54792  False     False     False  False            False  False
54793  False     False     False  False            False  False
54794  False     False     False  False            False  False

[54795 rows x 6 columns]

In [19]:
weather_df.isnull().sum()

date               0
temp_max           0
temp_min           0
rain               0
solar_radiation    0
city               0
dtype: int64

In [20]:
weather_df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
54790    False
54791    False
54792    False
54793    False
54794    False
Length: 54795, dtype: bool

In [21]:
weather_df.duplicated().sum()

np.int64(0)

In [22]:
weather_df["date"] = pd.to_datetime(weather_df["date"],errors="coerce")

In [23]:
weather_df["city"].value_counts()

city
Rawalpindi    3653
Islamabad     3653
Abbottabad    3653
Gilgit        3653
Skardu        3653
Lahore        3653
Faisalabad    3653
Sialkot       3653
Multan        3653
Bahawalpur    3653
Karachi       3653
Hyderabad     3653
Sukkur        3653
Quetta        3653
Gwadar        3653
Name: count, dtype: int64

In [24]:
weather_df["city"].value_counts().count()

np.int64(15)

In [25]:
print("Earliest date:", weather_df["date"].min())
print("Latest date:", weather_df["date"].max())
print("Number of unique cities:", weather_df["city"].nunique())

Earliest date: 2013-12-31 19:00:00+00:00
Latest date: 2023-12-31 19:00:00+00:00
Number of unique cities: 15